version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2204:current  # VM Ubuntu avec Docker installé

jobs:
  build:
    executor: machine-executor
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t $DOCKER_USERNAME/nodejs-image-demo .

  push:
    executor: machine-executor
    steps:
      - checkout
      - run:
          name: Se connecter à Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Tag et push de l’image Docker
          command: |
            docker tag nodejs-image-demo:latest $DOCKER_USERNAME/nodejs-image-demo:latest
            docker push $DOCKER_USERNAME/nodejs-image-demo:latest


workflows:
  version: 2
  build_and_run:
    jobs:
      - build
      - push:
          requires:
            - build
