version: 2.1  

jobs:
  test: 
    docker:
      - image: circleci/node:14  
    steps:
      - checkout  # Clone le repo dans le conteneur
      - run:
          name: Installer les dépendances
          command: npm install
      - run:
          name: Lancer les tests
          command: npm test

workflows:
  version: 2 
  test_and_build:
    jobs:
      - test 
