version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2204:current  # VM Ubuntu avec Docker installé

jobs:
  build:
    executor: machine-executor
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t nodejs-image-demo .
      - run:
          name: Vérifier que l'image a bien été créée
          command: docker images | grep nodejs-image-demo

  run_container:
    executor: machine-executor
    steps:
      - checkout
      - run:
          name: Lancer le conteneur
          command: docker run -d -p 8080:8080 nodejs-image-demo

workflows:
  version: 2
  build_and_run:
    jobs:
      - build
      - run_container:
          requires:
            - build
