version: 2.1  # Version CircleCI

executors:
  machine-executor:
    machine:
      image: ubuntu-2204:current  # VM Ubuntu 22.04 avec Docker préinstallé
    working_directory: ~/project

jobs:
  build:
    executor: machine-executor
    steps:
      - checkout  # Clone le repo dans la VM
      - run:
          name: Vérifier Docker
          command: docker --version
      - run:
          name: Build de l'image Docker
          command: |
            docker run -p 8080:8080 nodejs-image-demo:latest 
      - run:
          name: Lister les images Docker
          command: docker images


workflows:
  version: 2
  build_and_push:
    jobs:
      - build
